version: "3"

services:

  # ADMIN CLIENT ---------------------------------------------------------------------------- //
  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./admin/public:/app/admin/public
      - ./admin/src:/app/admin/src
    # command: npm run start
    # restart: always
#     networks:    
#       - shoppingstorenetwork

# networks:    
#   shoppingstorenetwork: