FROM node:alpine

RUN npm install -g nodemon

RUN mkdir -p /app/server

WORKDIR /app/server

COPY package*.json /app/server/

RUN npm install

RUN npm install jest -g

COPY . /app/server/

CMD ["npm","run", "dev"]