FROM node:12.2.0-alpine as builder

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN npm install

COPY . /usr/src/app

RUN npm run build

RUN npm install -g serve

EXPOSE 4000

CMD ["serve" , "-l", "4000", "-s", "build"]
